### ISSUE TITLE
Failed mirrors on specific non DM PRs with a single file type

### ISSUE THREAD

**Issue by LetterJay** [HippieStation/PRMirror#11]
Simply the mirror doesn't seem to play well with mirroring any PR that doesn't include a DM.

Example:
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/2650
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/2657

Both the original PRs only contain TGU files and DMI files.

**Comment by j-mie** [comment]
Did you modify the DMI files? Can you please post the log files for both of these mirrors.

**Comment by LetterJay** [comment]
2650: https://pastebin.com/S0xWhQG6
2657: https://pastebin.com/1cKVthem

Aside from upstream DMI files, no they shouldn't be modified.
